# Site settings
project: aiptv
baseurl: /AIPTV.bundle
email: manferwebs@gmail.com
github_username: manfer
bootstrap_theme: slate

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [with_toc_data]

